"""files

Revision ID: b59d55b5c5c4
Revises: 88c4e172ace6
Create Date: 2025-08-07 14:43:41.137967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59d55b5c5c4'
down_revision = '88c4e172ace6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_column('file_path')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
